name: "one_cask"
description: "A Flutter App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/splash_bg.png
    - assets/ic_logo.png
    - assets/whisky1.png

  fonts:
    - family: EB Garamond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
        - asset: fonts/Lato-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_logo.png" # Path to your icon
  adaptive_icon_background: "#0B1519" # Background color for Android adaptive icon
  adaptive_icon_foreground: "assets/ic_logo.png"


flutter_native_splash:
  color: "#0B1519"
  android_12:
    color: "#0B1519"
  android: true
  ios: true
  color_android: "#0B1519"
  color_dark_android: "#0B1519"
  color_ios: "#0B1519"
  color_dark_ios: "#0B1519"
